configs:
  secret:
    argocdServerAdminPasswordMtime: 2021-11-08T15:04:05Z
  cm:
    application.resourceTrackingMethod: annotation
    timeout.reconciliation: 60s
  params:
    server.insecure: true
repoServer:
  livenessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
  readinessProbe:
    timeoutSeconds: 5
server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: ''
  extraArgs:
  - --insecure
